name: Create preview environment

on:
  pull_request:
    branches: [ master ]

# TODO: Wait for main workflow to succeed before pushing a preview environment

concurrency:
  # The preview script can't handle concurrent deploys
  group: preview_deploy
  cancel-in-progress: false

# TODO: Define minimal permissions, I haven't found which one is necessary to allow writing comments on commits
# see https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
#permissions:
#  contents: read # for checkout

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking=no" > ~/.ssh/config
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Install ansible
        run: python3 -m pip install --user ansible

      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main

      - name: checkout
        uses: actions/checkout@v2

      - name: Create deploy scripts
        run: |
          mkdir -p ./scripts
          echo "$DEPLOY_PREVIEW_SCRIPT" > ./scripts/deploy-preview.sh
          chmod +x ./scripts/deploy-preview.sh
          echo "$SCALA_PREVIEW_SCRIPT" > ./scripts/PreviewEnv.scala
        shell: bash
        env:
          DEPLOY_PREVIEW_SCRIPT: ${{secrets.DEPLOY_PREVIEW_SCRIPT}}
          SCALA_PREVIEW_SCRIPT: ${{secrets.SCALA_PREVIEW_SCRIPT}}

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.1
        with:
          java-version: 'adopt:1.11.0-11'
          node-version: '16.7.0'

      - name: Compile
        run: sbt compile

      - name: Create preview env
        run: cd infra && ./scripts/deploy-preview.sh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_NUMBER: ${{ github.event.number }}